from typing_extensions import override

from .encoder_nodes import *
from .image_nodes import *
from .preset_nodes import *
from .vlm_nodes import *
from .parameter_nodes import *
from .utils_nodes import *
from .legacy_nodes import *
from .scheduler_nodes import *

from comfy_api.latest import ComfyExtension, io
from .node_replacements import register_replacements

class SamplingUtils(ComfyExtension):
    @override
    async def get_node_list(self) -> list[type[io.ComfyNode]]:
        return [
            UC_AdjustedResolutionParameters,
            UC_ResolutionSelectorExtended,
            UC_ImageScaleAndResolutionPicker,
            UC_Image_Color_Noise,
            UC_TextEncodeFlux2SystemPrompt,
            UC_TextEncodeKleinSystemPrompt,
            UC_TextEncodeKrea2SystemPrompt,
            UC_TextEncodeLtxv2SystemPrompt,
            UC_TextEncodeZITSystemPrompt,
            UC_TextEncodeZImageThinkPrompt,
            UC_TextEncodeSystemPrompt,
            UC_ScaledBiasTextEncodeFlux2SystemPrompt,
            UC_ScaledBiasTextEncodeKleinSystemPrompt,
            UC_ScaledBiasTextEncodeLtxv2SystemPrompt,
            UC_ScaledBiasTextEncodeZITSystemPrompt,
            UC_ScaledBiasTextEncodeZImageThinkPrompt,
            UC_ScaledBiasTextEncodeSystemPrompt,
            UC_ModifyMask,
            UC_ImageBlendByMask,
            UC_SystemMessagePresets,
            UC_SystemMessageVideoPresets,
            UC_InstructPromptPresets,
            UC_InstructPromptVideoPresets,
            UC_BonusPromptPresets,
            UC_BonusPromptVideoPresets,
            UC_EditTargetPresets,
            UC_EditOpPresets,
            UC_CameraShotPresets,
            UC_VLMSysInstrPresets,
            UC_VLMSysQueryAddPresets,
            UC_VLMSysInstrAdvPresets,
            UC_LegacyPromptPresets,
            UC_UnifiedPresets,
            UC_AttentionBiasTextEncode,
            UC_TagNormalizeCombine,
            UC_LoadImagePath,
            UC_LoadImageDirectory,
            UC_SwitchInverseNode,
            UC_SoftSwitchInverseNode,
            UC_IntegerRangeRandom,
            UC_ImageMatchPropertiesNode,
            UC_OpticalFlowComposite,
            UC_ImageInwardEdgeFill,
            UC_ImageIterativeStretchFill,
            UC_TextOverlayNode,
            UC_RandInt,
            UC_StaticInt,
            UC_RandIntRange,
            UC_TextGenerateQwen35SystemPrompt,
            UC_ColorConvertNode,
            UC_ExtractBoundingBox,
            UC_Krea2LayerProbe,
            UC_Krea2LayerAblator,
            UC_Krea2InputEmbeds,
            UC_Qwen3VLInputEmbeds,
            UC_EncoderNodesGuide,
            AdjustedResolutionParameters,
            ResolutionSelectorExtended,
            ImageScaleAndResolutionPicker,
            Image_Color_Noise,
            TextEncodeFlux2SystemPrompt,
            TextEncodeKleinSystemPrompt,
            TextEncodeLtxv2SystemPrompt,
            TextEncodeZITSystemPrompt,
            TextEncodeZImageThinkPrompt,
            TextEncodeSystemPrompt,
            ScaledBiasTextEncodeFlux2SystemPrompt,
            ScaledBiasTextEncodeKleinSystemPrompt,
            TextEncodeSystemEditPlus,
            TextEncodeSystemEditPlusAdvanced,
            TextEncodeKrea2SystemEditPlusAdvanced,
            TextEncodeEditPlusAdvanced,
            TextEncodeKrea2SystemEditScaledAdv,
            TextEncodeKrea2SysEditScaledAdvAttn,
            TextEncodeEditScaledAdv,
            TextEncodeGemmaSystemEditPlusAdvanced,
            ScaledBiasTextEncodeLtxv2SystemPrompt,
            ScaledBiasTextEncodeZITSystemPrompt,
            ScaledBiasTextEncodeZImageThinkPrompt,
            ScaledBiasTextEncodeSystemPrompt,
            ModifyMask,
            ImageBlendByMask,
            SystemMessagePresets,
            SystemMessageVideoPresets,
            InstructPromptPresets,
            InstructPromptVideoPresets,
            BonusPromptPresets,
            BonusPromptVideoPresets,
            EditTargetPresets,
            EditOpPresets,
            CameraShotPresets,
            VLMSysInstrPresets,
            VLMSysQueryAddPresets,
            VLMSysInstrAdvPresets,
            UnifiedPresets,
            AttentionBiasTextEncode,
            TagNormalizeCombine,
            SU_LoadImagePath,
            SU_LoadImageDirectory,
            SwitchInverseNode,
            SoftSwitchInverseNode,
            IntegerRangeRandom,
            ImageMatchPropertiesNode,
            OpticalFlowComposite,
            ImageInwardEdgeFill,
            ImageIterativeStretchFill,
            TextOverlayNode,
            RandInt,
            StaticInt,
            RandIntRange,
            TextGenerateQwen35SystemPrompt,
            ColorConvertNode,
            EncoderNodesGuide,
            Ideogram4SchedulerPreset,
        ]

    @override
    async def on_load(self) -> None:
        """Called by ComfyUI backend on startup to initialize resources and register API extensions."""
        await register_replacements()

async def comfy_entrypoint() -> SamplingUtils:
    return SamplingUtils()
